/**
 * Generates hook scripts for Claude Code SessionStart auto-retrieval.
 * Scripts load mindkeg context at the start of every session.
 *
 * NOTE: Always generates bash scripts, even on Windows.
 * Claude Code uses bash on all platforms.
 */

/** Generate a bash hook script (used on all platforms — Claude Code always runs bash). */
export function generateBashHook(): string {
  return `#!/bin/bash
# Mind Keg — SessionStart auto-retrieval hook
# Generated by: npx mindkeg-mcp init
# Loads persistent memory at the start of every Claude Code session.

REPO_PATH=$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")
export MINDKEG_REPO="$REPO_PATH"

OUTPUT=$(node --experimental-sqlite -e "
(async () => {
  try {
    const os = await import('node:os');
    const path = await import('node:path');
    const { DatabaseSync } = await import('node:sqlite');

    const dbPath = path.join(os.homedir(), '.mindkeg', 'brain.db');
    const db = new DatabaseSync(dbPath, { open: true, readOnly: true });

    const repo = process.env.MINDKEG_REPO || '';
    const workspace = path.dirname(repo) + '/';

    // Query learnings: repo-scoped, workspace-scoped, and global
    const stmt = db.prepare(
      'SELECT content, category FROM learnings WHERE status = ? AND (repository = ? OR workspace = ? OR (repository IS NULL AND workspace IS NULL)) ORDER BY updated_at DESC LIMIT 20'
    );
    const rows = stmt.all('active', repo, workspace);

    if (rows.length === 0) process.exit(0);

    const lines = ['Mind Keg Persistent Memory (from ~/.mindkeg/brain.db):', ''];
    for (const row of rows) {
      lines.push('- [' + row.category + '] ' + row.content);
    }
    lines.push('', 'These learnings were loaded from Mind Keg. Use get_context for more details or store to save new knowledge.');
    console.log(lines.join('\\n'));
  } catch (e) {
    // Silent failure — never block session startup
  }
})();
" 2>/dev/null)

if [ -n "$OUTPUT" ]; then
  echo "$OUTPUT"
fi

exit 0
`;
}

/** Generate the Claude Code settings.json hook configuration object. */
export function generateHookConfig(scriptPath: string): Record<string, unknown> {
  return {
    hooks: {
      SessionStart: [
        {
          matcher: '*',
          hooks: [
            {
              type: 'command',
              command: scriptPath,
              timeout: 10,
              statusMessage: 'Loading persistent memory...',
            },
          ],
        },
      ],
    },
  };
}
